### ISSUE TITLE
Events 1.2b + v5.0.6

### ISSUE THREAD

**Issue by diegolameira** [ibspoof/ng-iScroll#21]
How do I use events? Even those demos are broken about it, they don't alert on scroll end.

**Comment by RezaRahmati** [comment]
Please somebody fix the demo  :((((( I have been struggling with this for hours :(((

**Comment by tilk-theapp** [comment]
for me this binding trigger all the actions done in the screen (cordova on iPhone), not specifically scrollEnd.

```
$scope.$parent.myScroll['wrapper'].on('scrollEnd', function(){
$scope.loadMore(); 
});
```

**Comment by diegolameira** [comment]
Since this issue I left iScroll. instead I use idangero's swiper, kenwheeler's slick or simply just overflow-scrolling css property. I recommend any of these this if you're not dealing/worrying with legacy.

**Comment by diegolameira** [comment]
Since this issue I left iScroll. instead I use idangero's swiper, kenwheeler's slick or simply just overflow-scrolling css property. I recommend any of these this if you're not dealing/worrying with legacy.
